### PR TITLE
doc: credential need to be instanciante before use

### PR DESCRIPTION
**Pull request by mastilver**
closes: #25

### CODE REVIEW

**Comment by mastilver** [comment]
@ericelliott does it looks good
I wasn't sure if I should put `credential().hash` or leave it as it was

**Comment by ericelliott** [comment]
I'd call it `pw.*` rather than `credential().*` and clarify that `pw` refers to the credential instance created by the exported factory.

**Comment by mastilver** [comment]
:+1:

**Comment by mastilver** [comment]
@ericelliott how about that: https://github.com/ericelliott/credential/pull/40/files#diff-04c6e90faac2675aa89e2176d2eec7d8R59

**Comment by ericelliott** [comment]
Good enough. We should update it to use [rtype](https://github.com/ericelliott/rtype#reading-function-signatures), but that's a different issue. =)

**Pull request merged**
