### PR TITLE
fix #12 and fix #13 (update constant time string comparison)

### LINKED ISSUE #12: constantEquals is not constant time
The function

```javascript
constantEquals = function constantEquals(x, y) {
    var result = true,
      length = (x.length > y.length) ? x.length : y.length,
      i;

    for (i=0; i<length; i++) {
      if (x.charCodeAt(i) !== y.charCodeAt(i)) {
        result = false;
      }
    }
    return result;
  },
```

is not constant time. In particular, the assignment of result will add instructions to the loop when the characters are inequal, exposing timing signatures.

I will post a comment momentarily with a thought on a possibly better option.

### PR DESCRIPTION
**Pull request by tjconcept**
I've merged the work of @brianmhunt with my recent changes.

### CODE REVIEW

**Comment by ericelliott** [comment]
This looks like a drop in replacement for https://github.com/ericelliott/credential/pull/13. Should we close that one?

**Comment by tjconcept** [comment]
Yes, it is. It's basically just a rebasing of @brianmhunt's work.

And yes, it should automatically close issue and PR when merged.

**Comment by ericelliott** [comment]
Awesome. Thanks!

**Comment by ericelliott** [comment]
I'm OK to merge this once we have a statistics test.

**Comment by tjconcept** [comment]
@ericelliott heard anything from SO or other channels on this? I keep ending with the conclusion that hashes aren't vulnerable.

**Comment by ericelliott** [comment]
Nothing new... I'm reaching the same conclusion, but I don't feel confident making the call to pull the constant time from the code. Now that we have a constant time test, I'm cool with merging this. I haven't run the tests myself on this branch. If both of you have run them, one of you should press the merge button. =) I have some errands to run, or I'd do it right now.

**Comment by tjconcept** [comment]
I stumbled upon https://github.com/freewil/scmp through one of your earlier posts in another auth-related module and think it seems neat.

**Comment by brianmhunt** [comment]
Thanks @tjconcept -- scmp is the same idea as the comparison I wrote, but it it early-outs when one string lengths are inequal (which it should not).

**Comment by tjconcept** [comment]
@brianmhunt I see, but aren't hashes always same length?

**Comment by brianmhunt** [comment]
If one consistently uses the same hashing function then yes. If one varies the hashing function, the the hash size may change.

It would be a matter of principle more than practicality. On considering it, one can still get the key size from the top-end (i.e. by varying up the length of the posit as opposed to varying down), so I am not sure there is any extra value here.

A "strong" constant-time function will do e.g. 5k comparisons for every comparison. Regardless of key size the comparison takes the same (long) length of time.

**Comment by ericelliott** [comment]
Assume that early bailout on shorter hash matters. =)

**Comment by brianmhunt** [comment]
Yeah, I imagine some nefarious folks scanning a table for SHA-1 hashes (vs. SHA-256/etc).

**Comment by ericelliott** [comment]
OK... I pulled and tested this branch. Looks good to me.

**Pull request merged**
