### PR TITLE
fix(cli): use the new credential api

### PR DESCRIPTION
**Pull request by mastilver**

### CODE REVIEW

**Comment by ericelliott** [comment]
Are there any tests for this? There should be. );

**Comment by mastilver** [comment]
Can't agree more :smile: 
And the linter is ignoring this file as well. (this PR correct linting issue except the `process.exit`)

**Comment by ericelliott** [comment]
hmm...

**Comment by ericelliott** [comment]
Do you have time to implement some tests?

**Comment by mastilver** [comment]
It won't be before the week-end

**Comment by mastilver** [comment]
I've put some test around the the cli.
But I still don't understand how to use the cli...

this work:
`echo -n "my password" | credential hash - | credential verify - "my password"`

But if I do:
`credential hash password`

and then:
`credential verify <the previous output> password`
It's throwing me: `Unexpected token ':"w6iqo4XwaKPzWn7B541EW+kWeVmJ9bMMv3WNMPPutWuwwSdJecntnXDBFw Xc+MO/dtAFnZKkdg+bBPIjJOqUpKGJ"' in expression or statement.`

//cc @tjconcept

**Comment by mastilver** [comment]
I've deleted my previous comment (and opened an issue related to it)
The behavious is the same as before #37 
Tests have been added

**Pull request merged**
