### PR TITLE
Rely on iterations only to determine workload

### PR DESCRIPTION
**Pull request by tjconcept**
I'll be doing more work in this PR towards solving all of #14 and #11.

### CODE REVIEW

**Comment by tjconcept** [comment]
Do you have any automatic means of syncing documentation from code <-> readme?
It seems a bit of duplicate work effort.

**Comment by ericelliott** [comment]
Looking pretty good so far. I'll pull it down and run the tests asap. Ping me here if you don't hear back today.

**Comment by tjconcept** [comment]
I've followed the reference implementation you linked, but noticed that the amount of iterations is almost twice as many now.
This can be tweaked of course, but we should probably find some sane defaults.

**Comment by tjconcept** [comment]
The last commit is not breaking and can be rebased behind the other breaking, if desired.

I'll go to bed now (GMT +1), and be up in 8h :)

**Comment by ericelliott** [comment]
If anything, I think these iterations are too low. Some current botnets could check **half a million passwords per second** with these settings. Do that with a frequency sorted dictionary, and you're bound to crack a lot of passwords in a day. There's no way around it, though -- we're always going to be out-gunned.  [Passwords are obsolete](https://github.com/ericelliott/credential/issues/16).

I'm really thinking we should try to get people to offload their identity auth to a company who has massive resources and can afford to crank the work units sky high.

**Comment by ericelliott** [comment]
Let me know when you're happy with this PR. The changes look pretty good to me.

**Comment by tjconcept** [comment]
I'm good with it, feel free to merge/rebase.

> If anything, I think these iterations are too low

That's subjective, I just wanted to disclose that these are approx. twice as high as the current.

> I'm really thinking we should try to get people to offload their identity auth to a company who has massive resources and can afford to crank the work units sky high.

That would make a lot of sense, if it is feasible. Still it's just moving the problem around. On a more theoretical level I think you should never give up a static secret (such as a password) to any remote server. I personally use a CLI password manager that gives me a unique derived password for each application.
Substack has done some of the right work towards this in his https://github.com/substack/keyboot-ui - unlike him, I believe this is something browsers need to implement with a proper UI.
But for now, this module is still very much needed to increase the current situation.
Let's keep the discussion going in #16 on how we can (potentially in another module) support even better authentication - using 2FA, local stuff or by other means.

**Comment by ericelliott** [comment]
The guys who are running the botnets aren't purchasing time. They're pwning old Wordpress installs. ;)

**Comment by tjconcept** [comment]
Anything missing before merging?

**Comment by ericelliott** [comment]
LOL... got so caught up in the conversation I totally forgot to merge. =)

**Comment by tjconcept** [comment]
I'm thinking about creating a branch - one for `0.2.x` besides master - and write a small "upgrade notice" for the README to clarify that existing `< 0.3.x` users should follow `0.2.x` to the top and stay there until all passwords are either re-hashed or expired of natural courses.
The branches are actually API-compatible apart from the configuration and the last commit (`.expired`) is a no-op to backport to the `0.2.x`-branch.

What do you think about that?

**Comment by ericelliott** [comment]
No need to create a branch. We'll just push the release as 1.0.0.

**Comment by tjconcept** [comment]
It's primarily because I wanted to "backport" the `.expired` feature and maybe in the future keep that branch up-to-date as much as possible - to allow users with an existing db of hashes to keep along.
See my https://github.com/srcagency/credential/commits/v0.2.x branch.

**Comment by ericelliott** [comment]
> maybe in the future keep that branch up-to-date as much as possible - to allow users with an existing db of hashes to keep along.

Yep. If we want to update 0.x.x, we can branch at that time. No need to do it now. =)

**Comment by ericelliott** [comment]
P.S. I've made you a collaborator, but please continue to use the PR process to merge changes into Master. =)

**Pull request merged**
